spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: codingpractice789@gmail.com
    password: zfgr wiih upvw pina
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false

logging:
  level:
    org.springframework.mail: DEBUG
