spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: codingpratice789@gmail.com
    password: miuh puxm xexm oxns
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
